#!/bin/bash
# Very simple stack-like directory handler.

STACK_FILE="$HOME/.dstack.txt"

mode=$(echo $1 | tr '[A-Z]' '[a-z]');

if [ $mode = "push" ]; then

	if [ $# -gt 1 ]; then
		path=$2
	else
		path=$(pwd)
	fi

	echo $path >> $STACK_FILE
	
elif [ $mode = "pop" ]; then

	if [ -f $STACK_FILE ]; then
		lines=$(wc -l $STACK_FILE | cut -d ' ' -f 1)
	else
		echo "Nothing to pop."
		exit
	fi

	echo ">$lines"

	if [ $lines -eq 0 ]; then
		echo "Nothing to pop."
		exit
	fi

	path=$(tail -1 $STACK_FILE)
	cat $STACK_FILE | head -n -1 > $STACK_FILE
	cd $path

else
	printf "Usage: $0 <push | pop> [path]\nExample: $0 push\n\n";
fi
